create  databade if not exists asterisk character set utf8
collate utf8_general_ci;

use asterisk;

CREATE TABLE cdr (
calldate timestamp default CURRENT_TIMESTAMP,
clid varchar(80),
src varchar(80) ,
dst varchar(80) ,
dcontext varchar(80),
channel varchar(80),
dstchannel varchar(80),
lastapp varchar(80),
lastdata varchar(80),
duration int(11),
billsec int(11),
disposition varchar(45),
amaflags int(11),
accountcode varchar(20),
uniqueid varchar(32),
userfield varchar(255),
peeraccount varchar(20),
linkedid varchar(32),
sequence int(11)
) engine=InnoDB;

CREATE TABLE sippeers (
    id INTEGER NOT NULL AUTO_INCREMENT, 
    name VARCHAR(200) NOT NULL, 
    ipaddr VARCHAR(200), 
    port INTEGER, 
    regseconds INTEGER, 
    defaultuser VARCHAR(200), 
    fullcontact VARCHAR(200), 
    regserver VARCHAR(200), 
    useragent VARCHAR(200), 
    lastms INTEGER, 
    host VARCHAR(200), 
    type ENUM('friend','user','peer'), 
    context VARCHAR(200), 
    permit VARCHAR(200), 
    deny VARCHAR(200), 
    secret VARCHAR(200), 
    md5secret VARCHAR(200), 
    remotesecret VARCHAR(200), 
    transport ENUM('udp','tcp','tls','ws','wss','udp,tcp','tcp,udp'), 
    dtmfmode ENUM('rfc2833','info','shortinfo','inband','auto'), 
    directmedia ENUM('yes','no','nonat','update'), 
    nat VARCHAR(200), 
    callgroup VARCHAR(200), 
    pickupgroup VARCHAR(200), 
    language VARCHAR(200), 
    disallow VARCHAR(200), 
    allow VARCHAR(200), 
    insecure VARCHAR(200), 
    trustrpid ENUM('yes','no'), 
    progressinband ENUM('yes','no','never'), 
    promiscredir ENUM('yes','no'), 
    useclientcode ENUM('yes','no'), 
    accountcode VARCHAR(00), 
    setvar VARCHAR(200), 
    callerid VARCHAR(200), 
    amaflags VARCHAR(200), 
    callcounter ENUM('yes','no'), 
    busylevel INTEGER, 
    allowoverlap ENUM('yes','no'), 
    allowsubscribe ENUM('yes','no'), 
    videosupport ENUM('yes','no'), 
    maxcallbitrate INTEGER, 
    rfc2833compensate ENUM('yes','no'), 
    mailbox VARCHAR(200), 
    `session-timers` ENUM('accept','refuse','originate'), 
    `session-expires` INTEGER, 
    `session-minse` INTEGER, 
    `session-refresher` ENUM('uac','uas'), 
    t38pt_usertpsource VARCHAR(200), 
    regexten VARCHAR(200), 
    fromdomain VARCHAR(200), 
    fromuser VARCHAR(200), 
    qualify VARCHAR(200), 
    defaultip VARCHAR(200), 
    rtptimeout INTEGER, 
    rtpholdtimeout INTEGER, 
    sendrpid ENUM('yes','no'), 
    outboundproxy VARCHAR(200), 
    callbackextension VARCHAR(200), 
    timert1 INTEGER, 
    timerb INTEGER, 
    qualifyfreq INTEGER, 
    constantssrc ENUM('yes','no'), 
    contactpermit VARCHAR(200), 
    contactdeny VARCHAR(200), 
    usereqphone ENUM('yes','no'), 
    textsupport ENUM('yes','no'), 
    faxdetect ENUM('yes','no'), 
    buggymwi ENUM('yes','no'), 
    auth VARCHAR(200), 
    fullname VARCHAR(200), 
    trunkname VARCHAR(200), 
    cid_number VARCHAR(200), 
    callingpres ENUM('allowed_not_screened','allowed_passed_screen','allowed_failed_screen','allowed','prohib_not_screened','prohib_passed_screen','prohib_failed_screen','prohib'), 
    mohinterpret VARCHAR(200), 
    mohsuggest VARCHAR(200), 
    parkinglot VARCHAR(200), 
    hasvoicemail ENUM('yes','no'), 
    subscribemwi ENUM('yes','no'), 
    vmexten VARCHAR(200), 
    autoframing ENUM('yes','no'), 
    rtpkeepalive INTEGER, 
    `call-limit` INTEGER, 
    g726nonstandard ENUM('yes','no'), 
    ignoresdpversion ENUM('yes','no'), 
    allowtransfer ENUM('yes','no'), 
    dynamic ENUM('yes','no'), 
    path VARCHAR(256), 
    supportpath ENUM('yes','no'), 
    PRIMARY KEY (id), 
    UNIQUE (name)
) engine=InnoDB;



